version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb


  web:
    build: ./web
    command: gunicorn myportfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web:/app
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - web
    volumes:
      - ./web/static:/app/static



volumes:
  static:
  pg_data:

