# Generated by Django 3.2.6 on 2023-09-09 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='abilities',
            name='degree',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Min value should be 1 atleast'), django.core.validators.MaxValueValidator(100, message='Max value should be 100 most')]),
        ),
        migrations.AddField(
            model_name='abilities',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_abilities', to='api.profile'),
        ),
        migrations.AddField(
            model_name='abilities',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Pl'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_contacts', to='api.profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='projectcategories',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_projects', to='api.profile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_picture',
            field=models.ImageField(default=None, upload_to='', verbose_name='Project Image'),
        ),
        migrations.AddField(
            model_name='projects',
            name='referance_link',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_category', to='api.projectcategories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='company_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='description',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='end_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='position',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_works', to='api.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='referance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.referances'),
        ),
        migrations.AddField(
            model_name='workexperinces',
            name='referance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.referances'),
        ),
    ]
