# Generated by Django 3.2.6 on 2023-09-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230909_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='referances',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_referances', to='api.profile'),
        ),
    ]
