# Generated by Django 3.2.6 on 2023-09-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_referances_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilities',
            options={'verbose_name': 'Ability', 'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacnt', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='projectcategories',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='referances',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'Referances'},
        ),
        migrations.AlterModelOptions(
            name='workexperinces',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.AddField(
            model_name='projectcategories',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_project_categories', to='api.profile'),
            preserve_default=False,
        ),
    ]
