# Generated by Django 3.2.6 on 2023-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230910_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Project Image'),
        ),
    ]
