# Generated by Django 3.2.6 on 2023-09-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_projects_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperinces',
            name='referance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.referances'),
        ),
    ]
