# Generated by Django 3.2.6 on 2023-09-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
