# Generated by Django 3.2.6 on 2023-09-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230910_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperinces',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
