# Generated by Django 3.2.6 on 2023-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230910_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Ahmet', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Ahmet', max_length=100),
        ),
    ]
