# Generated by Django 3.2.6 on 2023-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='icon_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
